services:
  app:
    image: wyliebrown1990/interview-app:latest
    ports:
      - "5005:5000"
    environment:
      DATABASE_URL: "postgresql://wyliebrown:test123@postgres/interview_bot"
    volumes:
      - ./uploads:/code/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: wyliebrown
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: interview_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
